# Generated by Django 3.2.16 on 2025-03-20 07:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='Дата создания')),
                ('name', models.CharField(max_length=256, verbose_name='Название точки интереса')),
                ('description', models.CharField(max_length=256, verbose_name='Описание точки интереса')),
                ('location', models.IntegerField()),
                ('category', models.CharField(max_length=256, verbose_name='Категория места')),
            ],
            options={
                'verbose_name': 'Точка интереса',
                'verbose_name_plural': 'Точки интереса',
            },
        ),
        migrations.CreateModel(
            name='Routers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='Дата создания маршрута')),
                ('name', models.CharField(max_length=256, verbose_name='Название маршрута')),
                ('description', models.CharField(max_length=256, verbose_name='Описание маршрута')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала тура')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания маршрута')),
                ('is_public', models.BooleanField(verbose_name='Виден для всех?')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routers', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
        migrations.CreateModel(
            name='RoutePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='router_points', to='trail.pointsofinterest')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='router_points', to='trail.routers')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=256, verbose_name='Текс отзыва')),
                ('score', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='trail.routers', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='trail.routers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to=settings.AUTH_USER_MODEL, verbose_name='Избранное')),
            ],
            options={
                'verbose_name': 'Избранный маршрут',
                'verbose_name_plural': 'Избранные маршруты',
            },
        ),
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='Дата создания коллекции')),
                ('name', models.CharField(max_length=256, verbose_name='Название коллекции')),
                ('description', models.CharField(max_length=256, verbose_name='Описание коллекции')),
                ('is_public', models.BooleanField(verbose_name='Коллекция видна для всех?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL, verbose_name='Владелец коллекции')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
            },
        ),
        migrations.CreateModel(
            name='CollectionRouters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_routers', to='trail.collections')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_routers', to='trail.routers')),
            ],
        ),
    ]
