# Generated by Django 3.2.16 on 2025-03-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trail", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collections",
            name="created_at",
            field=models.DateField(
                auto_created=True, verbose_name="Дата создания коллекции"
            ),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="pub_date",
            field=models.DateField(auto_now_add=True, verbose_name="Дата добавления"),
        ),
        migrations.AlterField(
            model_name="routers",
            name="created_at",
            field=models.DateField(
                auto_created=True, verbose_name="Дата создания маршрута"
            ),
        ),
        migrations.AlterField(
            model_name="routers",
            name="end_date",
            field=models.DateField(verbose_name="Дата окончания маршрута"),
        ),
        migrations.AlterField(
            model_name="routers",
            name="start_date",
            field=models.DateField(verbose_name="Дата начала тура"),
        ),
    ]
