# Generated by Django 3.2.16 on 2025-03-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trail", "0002_auto_20250320_1528"),
    ]

    operations = [
        migrations.AddField(
            model_name="pointsofinterest",
            name="photo",
            field=models.ImageField(blank=True, upload_to="media/points/"),
        ),
        migrations.AddField(
            model_name="routers",
            name="photo",
            field=models.ImageField(blank=True, upload_to="media/routers/"),
        ),
    ]
