# Generated by Django 3.2.16 on 2025-03-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trail", "0003_auto_20250320_1550"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pointsofinterest",
            name="location",
            field=models.DecimalField(
                blank=True, decimal_places=16, max_digits=22, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pointsofinterest",
            name="photo",
            field=models.ImageField(blank=True, upload_to="media/routers/"),
        ),
    ]
