# Generated by Django 4.2 on 2025-03-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trail", "0004_auto_20250321_1102"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pointsofinterest",
            old_name="location",
            new_name="latitude",
        ),
        migrations.AddField(
            model_name="pointsofinterest",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=16, max_digits=22, null=True
            ),
        ),
    ]
