# Generated by Django 4.2 on 2025-04-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trail", "0006_alter_routers_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collections",
            name="created_at",
            field=models.DateField(
                auto_now_add=True, verbose_name="Дата создания коллекции"
            ),
        ),
        migrations.AlterField(
            model_name="pointsofinterest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
    ]
